### ISSUE TITLE
Feature: Issue Tracking System

### ISSUE THREAD

**Issue by TheBrambleShark** [LuzFaltex/Vigilante#1]
This is an issue to track the progress of the Issue Tracking System. If you would like to see a feature added, please open a new issue named `Issue Tracking - My Feature` where "My Feature" is a short description of what you'd like done. In the issue text, describe the enhancement further and your rationale. We'll add it to this issue.

* [ ] Issue Categories
  * [ ] Lost & Found
  * [ ] Status Report
  * [ ] General Note
* [ ] Issue status - Open and Closed
* [ ] UI
  * [ ] Display open issues at the top in that category
  * [ ] Display categories as tabs
  * [ ] Allow sticky issues to be displayed above tabs for easy access
  * [ ] Issue comments
  * [ ] Edit issues
    * [ ] Revision history (for auditing)
